name: Build MAUI-Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

env:
    DOTNETVERSION:  6.0.0-preview.7.21377.19
    
jobs:
  buildwindows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Visual Studio Preview
      shell: pwsh
      run: powershell .\build\install-vs.ps1
        
    - name: Add msbuild to PATH
      shell: pwsh
      run: |
        dotnet tool update -g dotnet-vs
        & echo "$(vs where preview --prop=InstallationPath)\MSBuild\Current\Bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          
    - name:  install .NET 6 preview
      shell: pwsh
      run: |
        $ProgressPreference = 'SilentlyContinue'
        Invoke-WebRequest -Uri "https://dot.net/v1/dotnet-install.ps1" -OutFile dotnet-install.ps1
        & .\dotnet-install.ps1 -Version ${{env.DOTNETVERSION}} -InstallDir "$env:ProgramFiles\dotnet\" -Verbose
        & dotnet --list-sdks
    
    - name: Install and Run maui-check Tool
      shell: pwsh
      run: |
        & dotnet tool update --global redth.net.maui.check
        & maui-check --preview --verbose --ci --non-interactive --fix --skip androidsdk --skip xcode --skip vswin --skip vsmac --skip edgewebview2
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
